---
title: "Analyses"
author: "Stefano Coretta"
date: "10/09/2021"
output:
  html_document:
    number_sections: true
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
theme_set(theme_light())
library(magrittr)
library(FactoMineR)
library(factoextra)
library(brms)
library(rnaturalearth)
library(sf)
library(tidygeocoder)
```

# Read data

```{r data}
headings_em <- read_csv("data/raw/headings-emilian.csv")
headings_eo <- read_csv("data/raw/headings-esperanto.csv")

emilian <- read_csv("data/raw/emilian-clean.csv", skip = 1, col_names = headings_em$new, na = c("", "NA", "na")) %>%
  mutate(
    understand = factor(understand, levels = c("NO", "AL", "50/50", "G", "VG")),
    speak = factor(speak, levels = c("NO", "AL", "50/50", "G", "VG"))
  )

esperanto <- read_csv("data/raw/esperanto-clean.csv", skip = 1, col_names = headings_eo$new, na = c("", "NA", "na")) %>%
  mutate(
    age = str_remove(age, "jaroj"),
    age = str_replace(age, "naskiĝis en la 1995a", "25"),
    age = as.numeric(age),
    understand = factor(understand, levels = c("NO", "AL", "50/50", "G", "VG")),
    speak = factor(speak, levels = c("NO", "AL", "50/50", "G", "VG"))
  )

emilianto <- bind_rows(
  emilian %>% mutate(language = "Emilian"),
  esperanto %>% mutate(language = "Esperanto")
) %>%
  mutate(
    # Fix coding error MD+ > MD
    languages_family = ifelse(languages_family == "MD+", "MD", languages_family),
    # Recode
    profession_2 = case_when(
      profession == "STUDENT" ~ "student",
      profession %in% c("RETIRED", "NOTIW") ~ "not in work",
      profession %in% c("ISCO-AGR", "ISCO-CLE", "ISCO-SER", "ISCO-LAB", "ISCO-ELE") ~ "unskilled",
      profession %in% c("ISCO-MAN", "ISCO-PRO", "ISCO-TEC", "ISCO-CRA", "ISCO-ARM") ~ "skilled"
    ),
    languages_family_2 = case_when(
      languages_family %in% c("BD", "MULTD", "BE", "MULTE") ~ "multi_e",
      languages_family %in% c("BO", "MULTO") ~ "multi_o",
      languages_family %in% c("MD", "ME") ~ "mono_e",
      languages_family %in% c("MI", "MO") ~ "mono_o",
    ),
    age_2 = case_when(
      age < 21 ~ "0-20",
      age < 41 ~ "21-40",
      age < 61 ~ "41-60",
      age > 60 ~ "61+"
    ),
    across(ends_with(c("_read", "_write")), function(.x) ifelse(str_detect(.x, "^Yes"), 1, 0)),
    across(starts_with(c("with_", "at_", "in_", "about_")), function(.x) ifelse(str_detect(.x, "^Yes"), 1, 0))
  ) %>%
  rowwise() %>%
  mutate(
    passive_comp = sum(c_across(ends_with("_read")), na.rm = TRUE),
    active_comp = sum(c_across(starts_with(c("with_", "at_", "in_", "about_")) | ends_with("_write")), na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    passive_comp = ifelse(understand %in% c("G", "VG"), passive_comp + 1, passive_comp),
    passive_prop = passive_comp / 13,
    active_prop = active_comp / 42
  )

lang_use <- bind_rows(
  emilian %>% mutate(language = "Emilian"),
  esperanto %>% mutate(language = "Esperanto")
) %>%
  select(id, age, understand, speak, read_write, language, educated:familiar) %>%
  mutate(
    understand = ordered(understand, levels = c("NO", "AL", "50/50", "G", "VG")),
    speak = ordered(speak, levels = c("NO", "AL", "50/50", "G", "VG")),
    across(educated:familiar, ~ as.ordered(.x)),
    mean_comp_raw = as.numeric(understand) +
      as.numeric(speak) +
      ifelse(read_write == "Yes", 5, 0),
    mean_comp = mean_comp_raw / 15
  ) %>%
 drop_na()

attitudes <- lang_use %>%
  select(educated:familiar)
```

# Emilian

## Participants

```{r em-gender}
emilian %>%
  ggplot(aes(gender)) +
  geom_bar()
```

```{r em-age}
emilian %>%
  ggplot(aes(age)) +
  geom_histogram()

emilian %>%
  ggplot(aes(age)) +
  geom_density()
```

```{r em-education}
emilian %>%
  ggplot(aes(education)) +
  geom_bar()
```

```{r em-age-edu}
emilian %>%
  ggplot(aes(age, education)) +
  geom_jitter(height = 0.2, alpha = 0.5)
```

```{r em-occupation}
emilian %>%
  count(profession) %>%
  ggplot(aes(reorder(profession, -n), n)) +
  geom_bar(stat = "identity")
```

```{r em-languages-family}
emilian %>%
  count(languages_family) %>%
  ggplot(aes(reorder(languages_family, -n), n)) +
  geom_bar(stat = "identity")
```

```{r em-languages-parents}
emilian %>%
  count(languages_parents) %>%
  ggplot(aes(reorder(languages_parents, -n), n)) +
  geom_bar(stat = "identity")
```

## Language

### Understand

```{r em-understand}
emilian %>%
  ggplot(aes(understand, fill = understand)) +
  geom_bar() +
  scale_fill_brewer(type = "div") +
  theme_dark()
```

```{r em-understand-gender}
emilian %>%
  ggplot(aes(understand, fill = gender)) +
  geom_bar()

emilian %>%
  ggplot(aes(understand, fill = gender)) +
  geom_bar(position = "fill")
```

```{r em-understand-age}
emilian %>%
  ggplot(aes(age, fill = understand)) +
  geom_histogram(binwidth = 5) +
  facet_grid(understand ~ .)
```

```{r em-understand-profession}
emilian %>%
  ggplot(aes(understand, fill = profession)) +
  geom_bar()

emilian %>%
  ggplot(aes(understand, fill = profession)) +
  geom_bar(position = "fill")
```

### Speak

```{r em-speak}
emilian %>%
  ggplot(aes(speak, fill = speak)) +
  geom_bar() +
  scale_fill_brewer(type = "div")
```

```{r em-speak-gender}
emilian %>%
  ggplot(aes(speak, fill = gender)) +
  geom_bar()

emilian %>%
  ggplot(aes(speak, fill = gender)) +
  geom_bar(position = "fill")
```

```{r em-speak-age}
esperanto %>%
  ggplot(aes(age, fill = speak)) +
  geom_histogram(binwidth = 5) +
  facet_grid(speak ~ .)
```

```{r em-speak-profession}
emilian %>%
  ggplot(aes(speak, fill = profession)) +
  geom_bar()

emilian %>%
  ggplot(aes(speak, fill = profession)) +
  geom_bar(position = "fill")
```



### Read and write

```{r em-read-write}
emilian %>%
  ggplot(aes(read_write, fill = read_write)) +
  geom_bar()
```

```{r em-read-write-gender}
emilian %>%
  ggplot(aes(read_write, fill = gender)) +
  geom_bar()

emilian %>%
  ggplot(aes(read_write, fill = gender)) +
  geom_bar(position = "fill")
```

```{r em-read-write-age}
emilian %>%
  drop_na(read_write) %>% 
  ggplot(aes(age, fill = read_write)) +
  geom_histogram(binwidth = 5) +
  facet_grid(read_write ~ .)
```

```{r em-read-write-profession}
emilian %>%
  ggplot(aes(read_write, fill = profession)) +
  geom_bar()

emilian %>%
  ggplot(aes(read_write, fill = profession)) +
  geom_bar(position = "fill")
```




### Attitude

```{r em-attitude}
emilian %>%
  select(educated:familiar) %>%
  pivot_longer(educated:familiar, names_to = "feature", values_to = "rating") %>%
  ggplot(aes(as.factor(rating), fill = as.factor(rating))) +
  geom_bar() +
  scale_fill_brewer() +
  facet_grid(. ~ feature)

emilian %>%
  select(educated:familiar) %>%
  pivot_longer(educated:familiar, names_to = "feature", values_to = "rating") %>%
  ggplot(aes(feature, fill = as.factor(rating))) +
  geom_bar(position = "fill") +
  scale_fill_brewer()
```

## Urban vs Rural

```{r em-rur}
emil_rur <- emilian %>%
  mutate(
    ru_ur = ifelse(
      str_detect(birth_place, "-RU"), "rural",
      ifelse(
        str_detect(birth_place, "-UR"), "urban",
        NA
      )
    )
  )

emil_rur_clean <- emil_rur %>%
  select(id, understand, speak, read_write, educated:familiar, ru_ur) %>%
  mutate(
    understand = ordered(understand, levels = c("NO", "AL", "50/50", "G", "VG")),
    speak = ordered(speak, levels = c("NO", "AL", "50/50", "G", "VG")),
    across(educated:familiar, ~ as.ordered(.x))
  ) %>%
 drop_na()
```

```{r em-rur-plot}
emil_rur %>%
  drop_na(ru_ur) %>%
  ggplot(aes(ru_ur, fill = understand)) +
  geom_bar()

emil_rur %>%
  drop_na(ru_ur) %>%
  ggplot(aes(ru_ur, fill = understand)) +
  geom_bar(position = "fill")
```


# Esperanto

## Participants

```{r eo-gender}
esperanto %>%
  ggplot(aes(gender)) +
  geom_bar()
```

```{r eo-age}
esperanto %>%
  ggplot(aes(age)) +
  geom_histogram()

esperanto %>%
  ggplot(aes(age)) +
  geom_density()
```

```{r eo-education}
esperanto %>%
  ggplot(aes(education)) +
  geom_bar()
```

```{r eo-age-edu}
esperanto %>%
  ggplot(aes(age, education)) +
  geom_jitter(height = 0.2, alpha = 0.5)
```

```{r eo-occupation}
esperanto %>%
  count(profession) %>%
  ggplot(aes(reorder(profession, -n), n)) +
  geom_bar(stat = "identity")
```

```{r eo-languages-family}
esperanto %>%
  count(languages_family) %>%
  ggplot(aes(reorder(languages_family, -n), n)) +
  geom_bar(stat = "identity")
```


## Language

### Understand

```{r eo-understand}
esperanto %>%
  ggplot(aes(understand, fill = understand)) +
  geom_bar() +
  scale_fill_brewer(type = "div") +
  theme_dark()
```

```{r eo-understand-gender}
esperanto %>%
  ggplot(aes(understand, fill = gender)) +
  geom_bar()

esperanto %>%
  ggplot(aes(understand, fill = gender)) +
  geom_bar(position = "fill")
```

```{r eo-understand-age}
esperanto %>%
  ggplot(aes(age, fill = understand)) +
  geom_histogram(binwidth = 5) +
  facet_grid(understand ~ .)
```

```{r eo-understand-profession}
esperanto %>%
  ggplot(aes(understand, fill = profession)) +
  geom_bar()

esperanto %>%
  ggplot(aes(understand, fill = profession)) +
  geom_bar(position = "fill")
```


### Speak

```{r eo-speak}
esperanto %>%
  ggplot(aes(speak, fill = speak)) +
  geom_bar() +
  scale_fill_brewer(type = "div")
```


```{r eo-speak-gender}
esperanto %>%
  ggplot(aes(speak, fill = gender)) +
  geom_bar()

esperanto %>%
  ggplot(aes(speak, fill = gender)) +
  geom_bar(position = "fill")
```

```{r eo-speak-age}
esperanto %>%
  ggplot(aes(age, fill = speak)) +
  geom_histogram(binwidth = 5) +
  facet_grid(speak ~ .)
```

```{r eo-speak-profession}
esperanto %>%
  ggplot(aes(speak, fill = profession)) +
  geom_bar()

esperanto %>%
  ggplot(aes(speak, fill = profession)) +
  geom_bar(position = "fill")
```

### Read and write

```{r eo-read-write}
esperanto %>%
  ggplot(aes(read_write, fill = read_write)) +
  geom_bar()
```


### Attitude

```{r eo-attitude}
esperanto %>%
  select(educated:familiar) %>%
  pivot_longer(educated:familiar, names_to = "feature", values_to = "rating") %>%
  drop_na() %>%
  ggplot(aes(as.factor(rating), fill = as.factor(rating))) +
  geom_bar() +
  scale_fill_brewer() +
  facet_grid(. ~ feature)

esperanto %>%
  select(educated:familiar) %>%
  pivot_longer(educated:familiar, names_to = "feature", values_to = "rating") %>%
  drop_na() %>%
  ggplot(aes(feature, fill = as.factor(rating))) +
  geom_bar(position = "fill") +
  scale_fill_brewer()
```


# Locations

```{r geo}
if (file.exists("./data/raw/geo.csv")) {
  cat("Reading geocoding...\n")
  geo <- read_csv("./data/raw/geo.csv")
} else {
  birth_em <- emilian %>% select(birth_place_it) %>% unique()
  geo <- geocode(birth_em, city = birth_place_it, method = "osm", verbose = TRUE)
  write_csv(geo, file = "./data/raw/geo.csv")
}
```


```{r europe}
europe <- ne_countries(continent = "Europe", returnclass = "sf", scale = "medium")
```

```{r emilian}
ggplot() +
  geom_sf(data = europe) +
  geom_point(data = geo, aes(long, lat)) +
  coord_sf(xlim = c(7, 14), ylim = c(43, 47))
```


# Modelling

## MCA

```{r attitudes-mca}
attitudes_mca <- MCA(attitudes, graph = FALSE)
attitudes_dims <- attitudes_mca[["ind"]][["coord"]]
```

```{r screeplot}
fviz_screeplot(attitudes_mca, addlabels = TRUE, ylim = c(0, 15))
fviz_mca_biplot(attitudes_mca, repel = TRUE)
```

```{r mca-cor}
fviz_mca_var(attitudes_mca, choice = "mca.cor", repel = TRUE)
```

```{r mca-var}
fviz_mca_var(attitudes_mca, col.var = "black", shape.var = 15, repel = TRUE)
```

```{r mca-var-cos2}
fviz_mca_var(attitudes_mca, col.var = "cos2", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)
```

```{r mca-cos2}
fviz_cos2(attitudes_mca, choice = "var", axes = 1:2)
```


```{r mca-contrib}
fviz_contrib(attitudes_mca, choice = "var", axes = 1, top = 15)
fviz_contrib(attitudes_mca, choice = "var", axes = 2, top = 15)
fviz_contrib(attitudes_mca, choice = "var", axes = 1:2, top = 15)
```

```{r mca-ind}
fviz_mca_ind(attitudes_mca, label = "none", habillage = "trustworthy")
fviz_mca_ind(attitudes_mca, label = "none", habillage = "friendly")
fviz_mca_ind(attitudes_mca, label = "none", habillage = "kind")
fviz_mca_ind(attitudes_mca, label = "none", habillage = "familiar")
```

```{r mca-dim1}
attitudes_mca$var$coord %>%
  as_tibble(rownames = "var") %>%
  separate(var, into = c("attitude", "score")) %>%
  ggplot(aes(-`Dim 1`, attitude, colour = score, size = score)) +
  geom_point() +
  scale_color_manual(values = c("#a6611a", "#dfc27d", "darkgrey", "#80cdc1", "#018571"))
```

```{r mca-dim2}
attitudes_mca$var$coord %>%
  as_tibble(rownames = "var") %>%
  separate(var, into = c("attitude", "score")) %>%
  ggplot(aes(`Dim 2`, attitude, colour = score, size = score)) +
  geom_point() +
  scale_color_manual(values = c("#a6611a", "#dfc27d", "darkgrey", "#80cdc1", "#018571"))
```


## Understand

```{r dim-1}
lang_use$dim_1 <- -attitudes_dims[, 1]
```

```{r understand-bm-prior}
get_prior(
  understand ~
    language * dim_1,
  data = lang_use,
  family = cumulative()
)

understand_priors <- c(
  prior(normal(0, 3), class = Intercept),
  prior(normal(0, 1), class = b)
)

understand_pchek <- brm(
  understand ~
    language * dim_1,
  data = lang_use,
  family = cumulative(),
  prior = understand_priors,
  sample_prior = "only",
  backend = "cmdstanr",
  cores = 4,
  file = "./data/rds/understand_pchek"
)

conditional_effects(understand_pchek, effects = "dim_1", conditions = make_conditions(lang_use, "language"), categorical = TRUE)
```


```{r understand-bm}
understand_bm <- brm(
  understand ~
    language * dim_1,
  data = lang_use,
  family = cumulative(),
  prior = understand_priors,
  backend = "cmdstanr",
  cores = 4,
  threads = threading(2),
  file = "./data/rds/understand_bm"
)
```

```{r understand-bm-sum}
understand_bm
summary(understand_bm, prob = 0.7)
```


```{r understand-bm-cond}
ubc <- conditional_effects(understand_bm, effects = "dim_1", categorical = TRUE, conditions = make_conditions(lang_use, "language"), plot = FALSE)
```

```{r understand-bm-cond-plot}
plot(ubc, plot = FALSE)[[1]] +
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_fill_brewer(type = "div", palette = "PRGn") +
  scale_color_brewer(type = "div", palette = "PRGn") +
  labs(
    x = "Attitude (MCA Dimension 1)",
    y = "Probability",
    caption = "Attidude is operationalised as the scores of Dimension 1 from the Multiple Correspondence Analysis.\nGreater values correspond to a more positive attitude.",
    colour = "Understand\ncompetence",
    fill = "Understand\ncompetence"
  )

ggsave("img/understand-brm.png", width = 7, height = 5)
```


## Speak

```{r speak-bm}
speak_bm <- brm(
  speak ~
    language * dim_1,
  data = lang_use,
  family = cumulative(),
  # Same priors as understand_bm
  prior = understand_priors,
  backend = "cmdstanr",
  cores = 4,
  threads = threading(2),
  file = "./data/rds/speak_bm"
)
```

```{r speak-bm-sum}
speak_bm
summary(speak_bm, prob = 0.4)
```


```{r speak-bm-cond}
sbc <- conditional_effects(speak_bm, effects = "dim_1", categorical = TRUE, conditions = make_conditions(speak_bm, "language"))
```

```{r speak-bm-cond-plot}
plot(sbc, plot = FALSE)[[1]] +
  scale_fill_brewer(type = "div", palette = "PRGn") +
  scale_color_brewer(type = "div", palette = "PRGn") +
  labs(
    x = "Attitude (MCA Dimension 1)",
    y = "Probability",
    caption = "Attidude is operationalised as the scores of Dimension 1 from the Multiple Correspondence Analysis.\nGreater values correspond to a more positive attitude.",
    colour = "Speaking\ncompetence",
    fill = "Speaking\ncompetence"
  )

ggsave("img/speak-brm.png", width = 7, height = 5)
```


## Read and write

```{r rw-bm}
rw_bm <- brm(
  read_write ~
    dim_1,
  data = lang_use %>% filter(language == "Emilian"),
  family = bernoulli(),
  # Same priors as understand_bm
  prior = understand_priors,
  backend = "cmdstanr",
  cores = 4,
  threads = threading(2),
  file = "./data/rds/rw_bm"
)
```

```{r rw-bm-sum}
rw_bm
```


```{r rw-bm-cond}
conditional_effects(rw_bm, effects = "dim_1")
```

## Mean competence

```{r meanc}
lang_use %>%
  ggplot(aes(mean_comp)) +
  geom_density() +
  geom_rug()
```

```{r meanc-jitter}
lang_use %>%
  ggplot(aes(language, mean_comp)) +
  geom_jitter(width = 0.2, alpha = 0.5, height = 0) +
  expand_limits(y = 0)
```   

```{r mean-jitter-dim}
lang_use %>%
  ggplot(aes(language, mean_comp, colour = dim_1)) +
  geom_jitter(width = 0.2, alpha = 0.5, height = 0) +
  expand_limits(y = 0)
```

```{r meanc-dim1}
lang_use %>%
  ggplot(aes(dim_1, mean_comp)) +
  geom_point() +
  facet_grid(~ language)
```

```{r meanc-bm}
mean_comp_bm <- brm(
  mean_comp ~
    language *
    dim_1,
  data = lang_use,
  family = zero_one_inflated_beta(),
  backend = "cmdstanr",
  cores = 4,
  file = "./data/rds/mean_comp_bm"
)

mean_comp_bm
```

```{r meanc-bm-cond}
conditional_effects(mean_comp_bm, effects = "dim_1:language")
```

## Dim-1 and age

```{r dim1-age}
lang_use %>%
  ggplot(aes(age, dim_1)) +
  geom_point() +
  geom_smooth(method = "lm")
```


## Rural vs urban

### Understand

```{r understand-rur}
understand_rur <- emil_rur_clean %>%
  count(understand, ru_ur) %>%
  group_by(ru_ur) %>%
  mutate(
    ru_ur_prop = n / sum(n)
  ) %>%
  ungroup() %>%
  mutate(
    understand = factor(understand, ordered = FALSE),
    ru_ur = factor(ru_ur, levels = c("rural", "urban"))
  )
```

```{r understand-rur-priors}
get_prior(
  n ~
    understand * ru_ur,
  data = understand_rur,
  family = Beta()
)
```

```{r understand-rur-bm}
understand_rur_priors <- c(
  prior(normal(0, 3), class = Intercept),
  prior(normal(0, 1), class = b)
)

understand_rur_bm <- brm(
  ru_ur_prop ~
    understand * ru_ur,
  data = understand_rur,
  family = Beta(),
  prior = understand_rur_priors,
  backend = "cmdstanr",
  cores = 4,
  threads = threading(2),
  file = "./data/rds/understand_rur_bm"
)

understand_rur_bm
```

```{r understand-rur-cond}
conditional_effects(understand_rur_bm, "understand:ru_ur")
```

### Speak

```{r speak-rur}
speak_rur <- emil_rur_clean %>%
  count(speak, ru_ur) %>%
  group_by(ru_ur) %>%
  mutate(
    ru_ur_prop = n / sum(n)
  ) %>%
  ungroup() %>%
  mutate(
    speak = factor(speak, ordered = FALSE),
    ru_ur = factor(ru_ur, levels = c("rural", "urban"))
  )
```


```{r speak-rur-bm}
speak_rur_bm <- brm(
  ru_ur_prop ~
    speak * ru_ur,
  data = speak_rur,
  family = Beta(),
  prior = understand_rur_priors,
  backend = "cmdstanr",
  cores = 4,
  file = "./data/rds/speak_rur_bm"
)

speak_rur_bm
```

```{r speak-rur-cond}
conditional_effects(speak_rur_bm, "speak:ru_ur")
```

### Read and write

```{r rw-rur}
rw_rur <- emil_rur_clean %>%
  count(read_write, ru_ur) %>%
  group_by(ru_ur) %>%
  mutate(
    ru_ur_prop = n / sum(n)
  ) %>%
  ungroup() %>%
  mutate(
    ru_ur = factor(ru_ur, levels = c("rural", "urban"))
  )
```


```{r rw-rur-bm}
rw_rur_bm <- brm(
  ru_ur_prop ~
    read_write * ru_ur,
  data = rw_rur,
  family = Beta(),
  prior = understand_rur_priors,
  backend = "cmdstanr",
  cores = 4,
  file = "./data/rds/rw_rur_bm"
)

rw_rur_bm
```

```{r rw-rur-cond}
conditional_effects(rw_rur_bm, "read_write:ru_ur")
```

# Tables and plots included in the paper

```{r tables}
columns <- c("gender", "age_2", "profession_2", "languages_family_2")

for (column in columns) {
  emilianto %>%
    group_by(language) %>%
    count(.data[[column]]) %>%
    mutate(
      prop = round(n / sum(n, na.rm = TRUE) * 100, 1)
    ) %>%
    pivot_wider(names_from = .data[[column]], values_from = c(n, prop)) %>%
    print()
}
```


```{r tables-2}
columns <- c("gender", "age_2", "profession_2", "languages_family_2")

for (column in columns) {
  emilianto %>%
    filter(
      understand %in% c("50/50", "G", "VG"),
      speak %in% c("50/50", "G", "VG")
    ) %>%
    group_by(language) %>%
    count(.data[[column]]) %>%
    mutate(
      prop = round(n / sum(n, na.rm = TRUE) * 100, 1)
    ) %>%
    pivot_wider(names_from = .data[[column]], values_from = c(n, prop)) %>%
    print()
}
```

```{r passive-active-prop}
competence <- emilianto %>%
  filter(gender != "LGBTQ+") %>%
  pivot_longer(c(passive_prop, active_prop), names_to = "competence", values_to = "proportion") %>%
  mutate(
    competence = recode_factor(competence, "passive_prop" = "passive", "active_prop" = "active")
  )
```

```{r pap-plot}
competence %>%
  ggplot(aes(gender, proportion, fill = gender)) +
  geom_hline(yintercept = 0, size = 0.25) +
  geom_hline(yintercept = 1, size = 0.25) +
  geom_violin(colour = NA, bw = 0.1) +
  geom_boxplot(width = 0.05, fill = "black", colour = "black") +
  stat_summary(colour = "white", fun = "median", geom = "point") +
  ylim(0, 1) +
  facet_grid(competence ~ language, labeller = as_labeller(list("competence" = c("a", "b")))) +
  scale_fill_brewer(type = "qual", palette = "Dark2") +
  labs(
    y = "Competence (proportion)",
    x = "Gender"
  ) +
  theme_minimal(base_size = 16) +
  theme(legend.position = "none")

ggsave("./img/competence.png", width = 7, height = 5)
```


